CREATE TABLE field_builds (digest TEXT PRIMARY KEY, agent TEXT NOT NULL, target TEXT NOT NULL, body TEXT NOT NULL, at DOUBLE PRECISION NOT NULL);
CREATE TABLE field_runs (id TEXT PRIMARY KEY, body TEXT NOT NULL, at DOUBLE PRECISION NOT NULL);
CREATE TABLE agent_memory (id TEXT PRIMARY KEY, agent TEXT NOT NULL, target TEXT NOT NULL, body TEXT NOT NULL, at DOUBLE PRECISION NOT NULL);
CREATE TABLE memory_reviews (id TEXT PRIMARY KEY, memory_id TEXT NOT NULL REFERENCES agent_memory(id), body TEXT NOT NULL);
CREATE TABLE field_duties (id TEXT PRIMARY KEY, body TEXT NOT NULL);
