CREATE TABLE joint_builds (digest TEXT PRIMARY KEY, body TEXT NOT NULL);
CREATE TABLE joint_missions (id TEXT PRIMARY KEY, opportunity TEXT NOT NULL UNIQUE, body TEXT NOT NULL, at DOUBLE PRECISION NOT NULL);
