CREATE TABLE learning_control (id TEXT PRIMARY KEY, body TEXT NOT NULL);
CREATE TABLE learning_cycles (id TEXT PRIMARY KEY, dedup_key TEXT NOT NULL UNIQUE, body TEXT NOT NULL, at DOUBLE PRECISION NOT NULL);
