# generated by datamodel-codegen:
#   filename:  core.schema.json

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class Build(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    digest: str
    manifest: Any
    variant: str


class Finding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: str
    file: str
    line: Annotated[int, Field(ge=0)]


class MissionInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    baseline: Build
    candidate: Build
    delay_seconds: Annotated[int, Field(ge=0)]
    id: str
    integration: bool


class Transition(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    detail: str
    state: str


class Trial(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    build_digest: str
    case_id: str
    elapsed_ms: Annotated[int, Field(ge=0)]
    findings: list[Finding]
    model: str
    requests: Annotated[int, Field(ge=0)]


class Mission(BaseModel):
    detail: str
    evidence: Any | None = None
    input: MissionInput
    stale: bool
    state: str
    updated_at: float


class Snapshot(BaseModel):
    missions: list[Mission]
    observed_at: float
    schema_version: Annotated[int, Field(ge=0)]
    simulation: bool


class Submission(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trials: list[Trial]


class Contract(BaseModel):
    input: MissionInput
    snapshot: Snapshot
    submission: Submission
    transition: Transition
