# generated by datamodel-codegen:
#   filename:  core.schema.json

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class FieldDuty(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    agent: str
    enabled: bool
    generation: Annotated[int, Field(ge=0)]
    id: str
    interval_seconds: Annotated[int, Field(ge=0)]
    target: str


class FieldInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    agent: str
    id: str
    inference: bool
    target: str


class Finding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: str
    key: str
    line: Annotated[int, Field(ge=0)]
    recommendation: str
    subject: str
    summary: str


class MemoryReview(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    decision: str
    id: str
    revision: Annotated[int, Field(ge=0)]


class RepositoryWatch(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    enabled: bool
    generation: Annotated[int, Field(ge=0)]
    interval_seconds: Annotated[int, Field(ge=0)]
    removed: bool
    repository: str


class FieldReport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    advisory: Any | None = None
    coverage: list[str]
    findings: list[Finding]
    memory: Any
    snapshot_digest: str


class FieldContract(BaseModel):
    duty: FieldDuty
    input: FieldInput
    memory_review: MemoryReview
    report: FieldReport
    repository_watch: RepositoryWatch
