# generated by datamodel-codegen:
#   filename:  core.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class JointBudget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    requests: Annotated[int, Field(ge=1, le=24)]
    tokens: Annotated[int, Field(ge=1, le=384000)]


class JointBuild(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    digest: str
    manifest: Any


class JointFinish(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    decision: Any | None = None
    reason: str


class JointLedgerBudget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    requests_limit: Annotated[int, Field(ge=0)]
    requests_reserved: Annotated[int, Field(ge=0)]
    tokens_accounted: Annotated[int, Field(ge=0)]
    tokens_limit: Annotated[int, Field(ge=0)]
    tokens_reserved: Annotated[int, Field(ge=0)]


class OpportunityCategory(StrEnum):
    diagnostic_fail = "diagnostic-fail"
    malformed_response = "malformed-response"
    unknown_usage_or_dispatch = "unknown-usage-or-dispatch"
    repeated_no_progress = "repeated-no-progress"
    budget_stop = "budget-stop"
    incomplete = "incomplete"


class OpportunityScope(StrEnum):
    public_simulation_review = "public-simulation-review"


class OpportunitySource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mission_id: str
    task_ids: list[str]
    tokens_accounted: Annotated[int, Field(ge=0)]
    usage_unknown: bool


class OpportunityStatus(StrEnum):
    proposed_review = "proposed-review"


class Role(StrEnum):
    lead = "lead"
    workload = "workload"
    service = "service"


class Scenario(StrEnum):
    route_mismatch = "route-mismatch"
    healthy = "healthy"
    persistent_dependency = "persistent-dependency"
    listening_but_broken = "listening-but-broken"


class TaskReservation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    focus: str | None = "overview"
    id: str
    question: Annotated[str, Field(max_length=2000, min_length=1)]
    role: Role
    round: Annotated[int, Field(ge=0, le=3)]
    tokens: Annotated[int, Field(ge=1, le=384000)]


class TaskStatus(StrEnum):
    completed = "completed"
    failed = "failed"
    unknown = "unknown"


class TrainerOpportunity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    accounting_overflow: bool
    build: str
    category: OpportunityCategory
    id: str
    most_recent_at: float
    observed_count: Annotated[int, Field(ge=0)]
    proposed_investigation: str
    scenario: str
    scope: OpportunityScope
    source_mission_ids: list[str]
    sources: list[OpportunitySource]
    status: OpportunityStatus
    tokens_accounted: Annotated[
        int | None,
        Field(
            description="Null on arithmetic overflow; exact per-mission amounts remain in sources.",
            ge=0,
        ),
    ] = None
    usage_unknown: bool


class Usage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    input_tokens: Annotated[int, Field(ge=0)]
    output_tokens: Annotated[int, Field(ge=0)]


class JointInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    budget: JointBudget
    build: str
    id: str
    inference: bool
    opportunity: str
    scenario: Scenario


class TaskResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    error: str | None = None
    output: Any
    status: TaskStatus
    trace: Any | None = None
    usage: Usage | None = None


class JointTask(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    accounted_tokens: Annotated[int, Field(ge=0)]
    eligible: bool
    focus: str
    id: str
    question: str
    reservation: TaskReservation
    result: TaskResult | None = None
    role: Role
    round: Annotated[int, Field(ge=0)]
    state: str
    tokens: Annotated[int, Field(ge=0)]


class JointClaim(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    dispatch: bool
    task: JointTask


class JointMission(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    budget: JointLedgerBudget
    build: JointBuild
    created_at: float
    deadline: float
    decision: Any | None = None
    finish: JointFinish | None = None
    input: JointInput
    learning_cycle: str | None = None
    outcome: str | None = None
    reason: str | None = None
    simulation: bool
    state: str
    tasks: list[JointTask]
    updated_at: float
    xp: Annotated[int, Field(ge=0)]


class JointSnapshot(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    builds: list[JointBuild]
    enabled: bool
    missions: list[JointMission]
    observed_at: float
    opportunities: Annotated[list[TrainerOpportunity] | None, Field(validate_default=True)] = []
    schema_version: Annotated[int, Field(ge=0)]
    simulation: bool


class JointContract(BaseModel):
    build: JointBuild
    claim: JointClaim
    finish: JointFinish
    input: JointInput
    mission: JointMission
    reservation: TaskReservation
    result: TaskResult
    snapshot: JointSnapshot
