# generated by datamodel-codegen:
#   filename:  core.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class JointBuild(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    digest: str
    manifest: Any


class LearningBudget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    proposal_requests: int = Field(..., ge=0)
    proposal_tokens: int = Field(..., ge=0)
    trial_requests: int = Field(..., ge=0)
    trial_tokens: int = Field(..., ge=0)


class LearningDuty(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    baseline: str
    budget: LearningBudget | None = Field(
        {
            "proposal_requests": 1,
            "proposal_tokens": 32768,
            "trial_requests": 24,
            "trial_tokens": 384000,
        },
        validate_default=True,
    )
    cooldown_seconds: int | None = Field(60, ge=0)
    enabled: bool | None = False
    generation: int = Field(..., ge=0)
    id: str
    max_cycles: int | None = Field(2, ge=0)


class LearningGrant(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    requests: int = Field(..., ge=0)
    tokens: int = Field(..., ge=0)


class PracticeIncumbent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    build: str
    generation: int = Field(..., ge=0)
    source_cycle: str | None = None


class PracticeRebase(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    at: float
    build: str
    duty_generation: int = Field(..., ge=0)
    incumbent_generation: int = Field(..., ge=0)
    previous_build: str


class Scenario(StrEnum):
    route_mismatch = "route-mismatch"
    healthy = "healthy"
    persistent_dependency = "persistent-dependency"
    listening_but_broken = "listening-but-broken"


class TaskStatus(StrEnum):
    completed = "completed"
    failed = "failed"
    unknown = "unknown"


class Usage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    input_tokens: int = Field(..., ge=0)
    output_tokens: int = Field(..., ge=0)


class LearningControl(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    admitted_cycles: int = Field(..., ge=0)
    duty: LearningDuty
    last_started_at: float | None = None
    practice_incumbent: PracticeIncumbent
    rebases: list[PracticeRebase] | None = Field([], validate_default=True)


class LearningTrial(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    arm: str
    mission_id: str
    pair: int = Field(..., ge=0)
    requests: int = Field(..., ge=0)
    scenario: Scenario
    slot: str
    tokens: int = Field(..., ge=0)


class ProcedureResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    error: str | None = None
    procedure: str | None = None
    rationale: str
    status: TaskStatus
    trace: Any | None = None
    usage: Usage | None = None


class LearningProposal(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    accounted_tokens: int = Field(..., ge=0)
    grant: LearningGrant
    result: ProcedureResult | None = None
    state: str


class LearningCycle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    baseline: JointBuild
    baseline_generation: int = Field(..., ge=0)
    budget: Any
    candidate: JointBuild | None = None
    created_at: float
    deadline: float
    dedup_key: str
    duty_generation: int = Field(..., ge=0)
    evidence_digest: str
    id: str
    policy: Any
    proposal: LearningProposal
    source_build: JointBuild
    source_missions: list[Any]
    source_opportunity: Any
    state: str
    summary: Any | None = None
    trial_order: list[str]
    trials: list[LearningTrial]
    updated_at: float


class LearningSnapshot(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    control: LearningControl | None = None
    cycles: list[LearningCycle]
    enabled: bool
    policy: Any
    schema_version: int = Field(..., ge=0)


class LearningContract(BaseModel):
    cycle: LearningCycle
    duty: LearningDuty
    proposal_result: ProcedureResult
    snapshot: LearningSnapshot
