# generated by datamodel-codegen:
#   filename:  core.schema.json

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class Crew(BaseModel):
    authority: str
    completed_runs: Annotated[int, Field(ge=0)]
    id: str
    name: str
    role: str
    xp: Annotated[int, Field(ge=0)]


class Duty(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    enabled: bool
    generation: Annotated[int, Field(ge=0)]
    id: str
    interval_seconds: Annotated[int, Field(ge=0)]
    profile: str
    target: str


class Execution(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    elapsed_ms: Annotated[int, Field(ge=0)]
    exit_code: int
    policy: Any
    stderr: str
    stdout: str


class Omission(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: str
    reason: str


class Proposal(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    inference: Any
    rationale: str
    source: str


class RegisteredBuild(BaseModel):
    digest: str
    manifest: Any


class RepairInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    mode: str
    scenario: str


class ReviewFinding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: str
    file: str
    line: Annotated[int, Field(ge=0)]
    message: str


class ReviewReport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    advisory: Any | None = None
    elapsed_ms: Annotated[int, Field(ge=0)]
    engine: str
    errors: list[Omission]
    files_reviewed: Annotated[int, Field(ge=0)]
    findings: list[ReviewFinding]
    model_calls: Annotated[int, Field(ge=0)]
    snapshot_digest: str


class RunEvent(BaseModel):
    at: float
    detail: str
    sequence: int
    state: str


class RunInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidate: str | None = None
    id: str
    inference: bool | None = False
    kind: str
    profile: str
    target: str


class SourceFile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: str
    sha256: str
    source: str


class SourceSnapshot(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    digest: str
    files: list[SourceFile]
    redaction: str
    skipped: list[Omission]


class Target(BaseModel):
    id: str
    label: str
    simulation: bool


class WorkerStatus(BaseModel):
    available: bool
    seen_at: float | None = None


class Action(BaseModel):
    attempts: Annotated[int, Field(ge=0)]
    digest: str
    inputs: list[Any]
    observation: Execution | None = None
    source: str
    stage: str
    state: str


class CaseTrial(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    case_id: str
    profile: str
    report: ReviewReport


class FrozenInput(BaseModel):
    builds: list[RegisteredBuild]
    request: RunInput


class RepairRecord(BaseModel):
    actions: list[Action]
    baseline: str
    build: Any
    created_at: float
    detail: str
    events: list[Any]
    expires_at: float
    input: RepairInput
    proposal: Proposal | None = None
    revision: str
    state: str
    summary: Any | None = None
    task: str


class RunReport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    review: ReviewReport | None = None
    trials: Annotated[list[CaseTrial] | None, Field(validate_default=True)] = []


class RetainedReport(BaseModel):
    evidence: RunReport | None = None
    summary: Any


class RunRecord(BaseModel):
    created_at: float
    detail: str
    events: Annotated[list[RunEvent] | None, Field(validate_default=True)] = []
    input: FrozenInput
    report: RetainedReport | None = None
    sequence: int
    snapshot: SourceSnapshot | None = None
    state: str
    updated_at: float


class OperationsSnapshot(BaseModel):
    active: list[RunRecord]
    builds: list[RegisteredBuild]
    crew: list[Crew]
    duties: list[Duty]
    field_runs: list[Any] | None = []
    observed_at: float
    progression: Any | None = None
    recent: list[RunRecord]
    repairs: Annotated[list[RepairRecord] | None, Field(validate_default=True)] = []
    schema_version: Annotated[int, Field(ge=0)]
    targets: list[Target]
    worker: WorkerStatus


class OperationsContract(BaseModel):
    duty: Duty
    run_input: RunInput
    run_record: RunRecord
    run_report: RunReport
    snapshot: OperationsSnapshot
    source_snapshot: SourceSnapshot
