"""Small process adapter to the pinned microsandbox CLI, not a sandbox implementation.

Only immutable input bytes cross into a disposable VM. No mounts, sockets, host
credentials, or networking. Each invocation has a runtime-enforced lifetime even
if this coordinator dies. Output is untrusted and bounded before parsing.
"""

import asyncio
import os
import platform
import re
import shutil
import tempfile
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
VERSION = "0.6.14"
# python:3.12.13-alpine, pinned by per-architecture manifest digest rather than the
# multi-architecture index so every build manifest names the exact executed image.
IMAGES = {
    "aarch64": "python@sha256:900229622a576409d52f7a66b24cf441415a828d7e503b0107bf56452a4e44ac",
    "x86_64": "python@sha256:aa679aa4eed6eb56c1dc6ad3f1b98b7d2d788fd961596779d188fdedad97fb38",
}


def image_for(machine: str) -> str:
    key = {"arm64": "aarch64", "amd64": "x86_64"}.get(machine, machine)
    if key not in IMAGES:
        raise RuntimeError(f"No qualified sandbox image for architecture {machine!r}")
    return IMAGES[key]


IMAGE = image_for(platform.machine())
POLICY: dict = {
    "runtime": "microsandbox",
    "version": VERSION,
    "image": IMAGE,
    "cpus": 1,
    "memory_mib": 256,
    "root_disk_mib": 256,
    "tmp_mib": 16,
    "command_seconds": 10,
    "lifetime_seconds": 30,
    "output_bytes": 32768,
    "network": "none",
    "user": "65534:65534",
    "host_mounts": [],
}


def environment() -> dict[str, str]:
    return {
        "PATH": os.environ.get("PATH", "/usr/bin:/bin:/opt/homebrew/bin"),
        "MSB_HOME": str(ROOT / ".local/microsandbox"),
        "LANG": "C.UTF-8",
    }


def executable() -> str:
    result = shutil.which("msb")
    if result is None:
        raise RuntimeError("microsandbox 0.6.14 is required; run just sandbox-doctor")
    return result


async def command(*args: str) -> tuple[int, bytes, bytes]:
    p = await asyncio.create_subprocess_exec(
        executable(),
        *args,
        env=environment(),
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    try:
        out, err = await asyncio.wait_for(p.communicate(), 15)
        return p.returncode or 0, out, err
    finally:
        if p.returncode is None:
            p.kill()
            await p.wait()


async def remove(name: str) -> None:
    # Names are generated by trusted callers and isolated by project MSB_HOME.
    if not re.fullmatch(r"sb-[a-z0-9-]{1,100}", name):
        raise ValueError("Invalid owned sandbox identity")
    code, output, error = await command("remove", "--force", name)
    error = output + error
    if code and b"not found" not in error.lower() and b"does not exist" not in error.lower():
        raise RuntimeError("Sandbox cleanup failed: " + error.decode(errors="replace")[:300])


async def run(name: str, source: str, *, seconds: int = 10) -> dict:
    """Execute a supplied Python program; callers must grade the returned bytes."""
    if len(source.encode()) > 24000 or not 1 <= seconds <= 10:
        raise ValueError("Sandbox input budget exceeded")
    started = time.monotonic()
    version = await command("--version")
    if version[0] or version[1].decode().strip().split()[-1].lstrip("v") != VERSION:
        raise RuntimeError("Unqualified microsandbox version")
    await remove(name)  # Reconcile an interrupted attempt before recreating its VM.
    with tempfile.TemporaryDirectory(prefix="starbase-input-") as directory:
        path = Path(directory) / "program.py"
        await asyncio.to_thread(path.write_text, source)
        p = await asyncio.create_subprocess_exec(
            executable(),
            "run",
            "--name",
            name,
            "--no-tty",
            "--pull",
            "never",
            "--net",
            "none",
            "--security",
            "restricted",
            "--user",
            POLICY["user"],
            "--cpus",
            "1",
            "--memory",
            "256M",
            "--root-disk",
            "256M",
            "--tmpfs",
            "/tmp:16M",
            "--timeout",
            f"{seconds}s",
            "--max-duration",
            "30s",
            "--rlimit",
            "nofile=64",
            "--rlimit",
            "nproc=32",
            "--rlimit",
            "fsize=8388608",
            "--rlimit",
            "as=134217728",
            "--copy-file",
            f"{path}:/program.py",
            "--workdir",
            "/tmp",
            IMAGE,
            "--",
            "python3",
            "-I",
            "-B",
            "/program.py",
            env=environment(),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )

        async def read(stream: asyncio.StreamReader | None) -> bytes:
            assert stream is not None
            data = bytearray()
            while chunk := await stream.read(4096):
                data.extend(chunk)
                if len(data) > POLICY["output_bytes"]:
                    raise ValueError("Sandbox output budget exceeded")
            return bytes(data)

        try:
            stdout, stderr, _ = await asyncio.wait_for(
                asyncio.gather(read(p.stdout), read(p.stderr), p.wait()), 40
            )
            result = {
                "exit_code": p.returncode,
                "stdout": stdout.decode(errors="replace"),
                "stderr": stderr.decode(errors="replace"),
                "policy": POLICY,
                "elapsed_ms": int((time.monotonic() - started) * 1000),
            }
        finally:
            if p.returncode is None:
                p.kill()
                await p.wait()
            # Cleanup errors must prevent a verified completion.
            await asyncio.shield(remove(name))
    return result
