# generated by datamodel-codegen:
#   filename:  core.schema.json

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class DiscoveryInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    build: Any
    capability_digest: str
    observed_at: float
    opportunity: str
    outcome: str
    reason: str
    repository: str
    revision: str | None = None
    source_digest: str | None = None


class FeedbackInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    captured: Any
    digest: str
    head: str
    observed_at: float
    proposal: Any


class SdlcEffect(BaseModel):
    data: Any
    key: str
    kind: str


class SdlcEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: Any
    key: str
    stage: str


class SdlcInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    build: Any
    capability_digest: str | None = None
    id: str
    opportunity: str
    repository: str
    revision: str


class SdlcPolicy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    enabled: bool
    expires_at: float
    generation: Annotated[int, Field(ge=0)]
    max_missions: Annotated[int, Field(ge=0)]
    publish: bool
    repository: str


class SdlcPrObservation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    head: str
    number: Annotated[int, Field(ge=0)]
    observed_at: float
    state: str


class SdlcPublication(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact_digest: str
    revision: str


class SdlcRetry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    build: Any
    id: str


class SdlcVerificationInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    build: Any
    feedback_digest: str | None = None
    head: str
    id: str


class SdlcContract(BaseModel):
    discovery: DiscoveryInput
    effect: SdlcEffect
    event: SdlcEvent
    feedback: FeedbackInput
    input: SdlcInput
    policy: SdlcPolicy
    pr_observation: SdlcPrObservation
    publication: SdlcPublication
    retry: SdlcRetry
    verification: SdlcVerificationInput
