# generated by datamodel-codegen:
#   filename:  core.schema.json

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class DiscoveryInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    build: Any
    capability_digest: str
    observed_at: float
    opportunity: str
    outcome: str
    reason: str
    repository: str
    revision: str | None = None
    source_digest: str | None = None


class FeedbackInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    captured: Any
    digest: str
    head: str
    observed_at: float
    proposal: Any


class SdlcCaseResults(BaseModel):
    failed: list[str]
    passed: list[str]


class SdlcCoordinationSummary(BaseModel):
    admission: str
    can_discover: bool
    reserved_opportunities: list[str]
    resolution: str


class SdlcDiffStats(BaseModel):
    additions: Annotated[int, Field(ge=0)]
    deletions: Annotated[int, Field(ge=0)]
    files: Annotated[int, Field(ge=0)]


class SdlcEffect(BaseModel):
    data: Any
    key: str
    kind: str


class SdlcEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: Any
    key: str
    stage: str


class SdlcEventSummary(BaseModel):
    at: float | None = None
    key: str
    label: str
    role: str | None = None
    stage: str


class SdlcGradingSummary(BaseModel):
    baseline_pass: bool | None = None
    candidate_pass: bool | None = None
    verdict: str | None = None


class SdlcInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    build: Any
    capability_digest: str | None = None
    id: str
    opportunity: str
    repository: str
    revision: str


class SdlcInputSummary(BaseModel):
    build_digest: str | None = None
    capability_digest: str | None = None
    id: str
    opportunity: str | None = None
    repository: str | None = None
    revision: str | None = None


class SdlcPage(BaseModel):
    limit: Annotated[int, Field(ge=0)]
    next_before: str | None = None
    order: str
    returned: Annotated[int, Field(ge=0)]
    total: Annotated[int, Field(ge=0)]


class SdlcPlanEvidence(BaseModel):
    decision: str | None = None
    rationale: str | None = None
    role: str | None = None
    task: str | None = None


class SdlcPolicy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    enabled: bool
    expires_at: float
    generation: Annotated[int, Field(ge=0)]
    max_missions: Annotated[int, Field(ge=0)]
    publish: bool
    repository: str


class SdlcPrObservation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    head: str
    number: Annotated[int, Field(ge=0)]
    observed_at: float
    state: str


class SdlcPublication(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact_digest: str
    revision: str


class SdlcPublicationSummary(BaseModel):
    branch: str | None = None
    pr_number: Annotated[int | None, Field(ge=0)] = None
    pr_observed_at: float | None = None
    pr_state: str | None = None
    pr_url: str | None = None
    state: str


class SdlcRetry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    build: Any
    id: str


class SdlcReviewFinding(BaseModel):
    evidence: str | None = None
    line: Annotated[int | None, Field(ge=0)] = None
    path: str | None = None
    problem: str | None = None


class SdlcTestingEvidence(BaseModel):
    artifact_digest: str | None = None
    baseline_cases: SdlcCaseResults | None = None
    candidate_cases: SdlcCaseResults | None = None
    diff: SdlcDiffStats | None = None
    grading: SdlcGradingSummary | None = None
    validation_error: str | None = None
    verdict: str | None = None


class SdlcVerificationInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    build: Any
    feedback_digest: str | None = None
    head: str
    id: str


class SdlcVerificationInputSummary(BaseModel):
    build_digest: str | None = None
    feedback_digest: str | None = None
    head: str | None = None


class SdlcVerificationSummary(BaseModel):
    cancel_requested: bool
    id: str
    input: SdlcVerificationInputSummary
    outcome: str | None = None
    policy_generation: Annotated[int | None, Field(ge=0)] = None
    state: str
    updated_at: float | None = None


class SdlcReviewEvidence(BaseModel):
    findings: list[SdlcReviewFinding] | None = None
    findings_truncated: bool
    missing_evidence: str | None = None
    rationale: str | None = None
    role: str | None = None
    status: str | None = None


class SdlcStageEvidence(BaseModel):
    plan: SdlcPlanEvidence | None = None
    reviewing: SdlcReviewEvidence | None = None
    testing: SdlcTestingEvidence | None = None


class SdlcMissionSummary(BaseModel):
    assigned_crew: dict[str, Any] | None = None
    cancel_requested: bool
    created_at: float | None = None
    current_stage: str | None = None
    event_count: Annotated[int, Field(ge=0)]
    id: str
    input: SdlcInputSummary
    latest_event: SdlcEventSummary | None = None
    objective: str | None = None
    policy_generation: Annotated[int | None, Field(ge=0)] = None
    publication: SdlcPublicationSummary
    recent_events: list[SdlcEventSummary]
    repository: str | None = None
    retry_of: str | None = None
    revision_count: Annotated[int, Field(ge=0)]
    stage_evidence: SdlcStageEvidence
    state: str
    updated_at: float | None = None
    verdict: str | None = None
    verifications: list[SdlcVerificationSummary]


class SdlcSnapshot(BaseModel):
    capability_catalog: Any
    coordination: SdlcCoordinationSummary
    discovery_count: Annotated[int, Field(ge=0)]
    enabled: bool
    missions: list[SdlcMissionSummary]
    page: SdlcPage
    policy: SdlcPolicy
    schema_version: Annotated[int, Field(ge=0)]
    verification_enabled: bool
    view: str


class SdlcContract(BaseModel):
    discovery: DiscoveryInput
    effect: SdlcEffect
    event: SdlcEvent
    feedback: FeedbackInput
    input: SdlcInput
    mission_summary: SdlcMissionSummary
    policy: SdlcPolicy
    pr_observation: SdlcPrObservation
    publication: SdlcPublication
    retry: SdlcRetry
    snapshot: SdlcSnapshot
    stage_evidence: SdlcStageEvidence
    verification: SdlcVerificationInput
