extends SceneTree
## Pinned export-stage repair for random node IDs generated by Godot's GLB importer.
## Never run against the checkout: only imported PackedScenes in an isolated stage.

func fail(message: String) -> void:
	push_error(message)
	quit(1)

func semantic_text(path: String) -> String:
	var text := FileAccess.get_file_as_string(path)
	var pattern := RegEx.new()
	pattern.compile("(?m)^(\\[node[^\\n\\]]*) unique_id=[0-9]+")
	text = pattern.sub(text, "$1", true)
	# Text saves invent local resource labels for each destination. Canonicalize
	# labels and their references together; retain paths, properties and graph shape.
	for kind in ["ext", "sub"]:
		pattern.compile("(?m)^\\[" + kind + "_resource [^\\n]* id=\"([^\"]+)\"[^\\n]*\\]")
		var matches := pattern.search_all(text)
		for i in range(matches.size()):
			var match := matches[i]
			var old := match.get_string(1)
			var stable: String = kind + "_canonical_" + str(i)
			text = text.replace(match.get_string(), match.get_string().replace("id=\"" + old + "\"", "id=\"" + stable + "\""))
			var constructor := "ExtResource" if kind == "ext" else "SubResource"
			text = text.replace(constructor + "(\"" + old + "\")", constructor + "(\"" + stable + "\")")
	return text

func _initialize() -> void:
	var project := ProjectSettings.globalize_path("res://")
	if not project.contains("/.local/starbase2-world-web-"):
		fail("Node-ID normalization requires an isolated Web export stage")
		return
	if Engine.get_version_info().hash != "ed1daf0bf001b61586d9930840f2f1394092c079":
		fail("Unexpected Godot revision for imported-scene normalization")
		return
	var args := OS.get_cmdline_user_args()
	if args.size() != 1:
		fail("Expected a normalization report path")
		return
	var files := DirAccess.get_files_at("res://.godot/imported")
	files.sort()
	var records: Array[Dictionary] = []
	var scratch_before := args[0].get_base_dir().path_join("normalize-before.tscn")
	var scratch_after := args[0].get_base_dir().path_join("normalize-after.tscn")
	for file in files:
		if not file.ends_with(".scn"): continue
		var path := "res://.godot/imported/" + file
		var packed := ResourceLoader.load(path) as PackedScene
		if packed == null:
			fail("Cannot load imported scene: " + path)
			return
		var bundled: Dictionary = packed.get("_bundled")
		var state := packed.get_state()
		if not bundled.has("node_ids") or bundled.node_ids.size() != state.get_node_count() or not bundled.id_paths.is_empty() or not bundled.editable_instances.is_empty():
			fail("Unsupported imported scene identity layout: " + path)
			return
		var before := bundled.duplicate()
		before.erase("node_ids")
		if ResourceSaver.save(packed, scratch_before) != OK:
			fail("Cannot retain pre-normalization semantic scene")
			return
		var ids := PackedInt32Array()
		var seen: Dictionary = {}
		for i in range(state.get_node_count()):
			if state.get_node_instance(i) != null:
				fail("Imported scene instances require separate identity review: " + path)
				return
			var identity := (path + "#" + str(state.get_node_path(i))).sha256_buffer()
			var id := int(identity.decode_u32(0) & 0x7fffffff)
			if id == 0 or seen.has(id):
				fail("Imported node-ID collision: " + path)
				return
			seen[id] = true
			ids.append(id)
		bundled.node_ids = ids
		packed.set("_bundled", bundled)
		var after: Dictionary = packed.get("_bundled")
		after.erase("node_ids")
		if before != after:
			fail("Normalization changed non-identity scene data: " + path)
			return
		var before_hash := FileAccess.get_sha256(path)
		var result := ResourceSaver.save(packed, path, ResourceSaver.FLAG_COMPRESS)
		if result != OK:
			fail("Cannot save normalized scene: " + path)
			return
		var persisted := ResourceLoader.load(path, "PackedScene", ResourceLoader.CACHE_MODE_IGNORE_DEEP) as PackedScene
		if persisted == null or persisted.get("_bundled").node_ids != ids or ResourceSaver.save(persisted, scratch_after) != OK:
			fail("Persisted imported scene identity verification failed: " + path)
			return
		var original_text := semantic_text(scratch_before)
		var persisted_text := semantic_text(scratch_after)
		if original_text != persisted_text:
			fail("Persisted non-identity scene data changed; inspect retained normalize-before/after.tscn: " + path)
			return
		records.append({"path": path, "nodes": ids.size(), "before_sha256": before_hash, "after_sha256": FileAccess.get_sha256(path), "semantic_sha256": persisted_text.sha256_text(), "persisted_verified": true})
	DirAccess.remove_absolute(scratch_before)
	DirAccess.remove_absolute(scratch_after)
	var report := FileAccess.open(args[0], FileAccess.WRITE)
	if report == null:
		fail("Cannot write normalization report")
		return
	report.store_string(JSON.stringify({"policy": "sha256-import-path-and-node-path-31-bit-v1", "scenes": records}, "  ") + "\n")
	report.close()
	print("Normalized imported node IDs in ", records.size(), " staged PackedScenes; non-identity scene data unchanged")
	quit()
